
[functions.parcel-pickup]
enabled = true
verify_jwt = true
import_map = "./functions/parcel-pickup/deno.json"
entrypoint = "./functions/parcel-pickup/index.ts"

[functions.notification-worker]
enabled = true
verify_jwt = true
import_map = "./functions/notification-worker/deno.json"
entrypoint = "./functions/notification-worker/index.ts"

[functions.welcome-email]
enabled = true
verify_jwt = true
entrypoint = "./functions/welcome-email/index.ts"
